image: dock.mau.dev/maubot/maubot

stages:
- build

variables:
  PYTHONPATH: /opt/maubot

build:
  stage: build
  except:
  - tags
  script:
  - python3 -m maubot.cli build -o xyz.maubot.reminder.mbp
  artifacts:
    paths:
    - "*.mbp"

build tags:
  stage: build
  only:
  - tags
  script:
  - python3 -m maubot.cli build -o xyz.maubot.reminder.mbp
  artifacts:
    paths:
    - "*.mbp"
